# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Juricaf
    description:  La jurisprudence francophone des cours suprêmes
    keywords:     jurisprudence, cassation, cour, suprême, francophone, francophonie, ahjucaf, arrêt, décision
    language:     fr
    #robots:       index, follow

  stylesheets:    [main.css, print.css: { media: print }, jquery-ui-1.8.16.custom.css]

  javascripts:    [jquery-1.6.1.min.js, jquery.scrollTo-min.js, jquery-ui-1.8.16.custom.min.js]

  has_layout:     true
  layout:         layout
